# Generated by Django 5.2.1 on 2025-05-22 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('floor', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=50)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Flat_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.flat')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('floors', models.IntegerField()),
                ('jk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='main.jk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='main.house'),
        ),
        migrations.CreateModel(
            name='House_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.house')),
            ],
        ),
        migrations.CreateModel(
            name='Jk_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('jk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.jk')),
            ],
        ),
    ]
